In [4]:
task1=pd.read_csv('youtube_channel_videos_T1.csv')
task2=pd.read_csv(r'Dataset/Task2/Aniket__Dataset_T2.csv')

In [1]:
import pandas as pd

In [5]:
task2

       Video_ID                                         Transcript
0   r4loBN9ffls  entry-level job as a data analyst has become m...
1   NVpxN1vAbNM  This is the biggest news in tech right now. Ye...
2   yg_K45YtzSs  Difference between a data engineer and a data ...
3   xoptBxQvIT0  [Music] Do you wish you were laid off? Assume ...
4   w9k1oXwiOJY  How do you actually stand out in the job marke...
5   CIfjV-q-g6M  I'm the coolest person in the room. Cuz you sp...
6   Uxr3sbB6h-c  Three reasons to not become a data engineer. N...
7   PcYZyb93Peg  Difference between a data scientist and a soft...
8   n08nWEvdz-I  Hi, what's your name and what do you do for a ...
9   4uHyKtxS1j8  AI engineer versus prompt engineer. What's the...
10  z8kAQPEVanw  Data scientist versus software engineer interv...
11  _rOwhGL7Hx4  Difference between data analyst, data scientis...
12  4Fjc1eOj58k  You spent four years at Google. Now you are at...
13  YOBpAHkuprE  10 learnings from 10 years in tech all in one ...
14  MJm_UsF1HJg  If somebody's telling you you can get that job...
15  nY9UdHZbyxc  I can't believe this AI tool is free. It's lit...
16  lLCVMc0fIOQ  Why do so many self-taught coders fail or get ...
17  ACN21XGzG2w  Microsoft just laid off 9,000 employees, which...
18  8_EYTERZ1Ko  Seven things that are holding you back in your...
19  mmybiM8W8c0  Hi, what's your name and what do you do for a ...
20  q76HaJHuQNc  AI isn't just about side projects anymore. It'...
21  wGiLecwYQrw  The worst salary negotiation mistake I have ma...
22  Ssl_zIc4FPY  The difference between a 90K and a 200K data a...
23  Gs7ToLkQv_8  This is the only video you need to watch to ca...
24  6Fr-HAzyyzA  Data scientist versus software engineering roa...
25  _aSAxamhd3A  story time of how I dodged the biggest bullet....
26   tyj8eNayRM  Who in the world leaves their job at Google as...
27  BH8hpkOI9l0  Okay, no gatekeeping. Name one life-changing r...
28  G-wildReV6w  If you're not using a coding AI agent yet, you...
29  oRR69xADBOE  What do you do for a living? I'm a software en...
30  n5GcunxVkxg  Things I don't care about. Tech edition. The 1...
31  mbYf_6XTgFY  Hi, what's your name and what do you do for a ...
32  DPGFwL4OE-A  You are officially an astronaut. Thank you so ...
33  BF9yShzrok0  Difference between a data engineer and a data ...
34  BFxy9CtHXrU  If you're trying to upskill as a data analyst,...
35  qxD38vaiX14  I paid $200 to try out OpenAI's first AI agent...
36  Vt4sbBeodKk  main language that you will be using as a data...
37  r9UF-NB1QiI  coding languages python is by far the number o...
38  CX8BmrbenU8  operator looks like the use case that I have t...
39   vsloDWDA_8  Whoever has been saying that AI agents are the...
40  r6S3egd8kPI  I use an AI agent to apply to 100 jobs without...
41  SqTTvrBQm7I  getting a call back in today's job market is a...
42  7bMnnFsO_sg  10e salary progression in less than 60 seconds...
43  _Gdj1NHakhs  in case you're looking for your next career op...
44  ELGjEHefi4w  since November 2022 not a single day where we ...
45  2r57BkWFLfQ  first we had work from home then we had quiet ...
46  RE7-goTKAz4  in case you missed the news meta recently fire...
47  9OA757v4FAM  in 2008 the term data scientist was coined and...
48  RrZ-Knp7p1s  10 years of learning from 10 years in Tech all...
49  MLidfb72Ue0  genz are difficult to work with they are unpro...

In [7]:
filtered_df = task1[task1['id'].isin(task2['Video_ID'])]

In [46]:
new_df=filtered_df[:50]

In [9]:
filtered_df.to_csv('Task1_Dataset_50_filtered.csv',index=False)

In [8]:
filtered_df

,id,title,description,publishedAt,tags,categoryId,defaultLanguage,defaultAudioLanguage,thumbnail_default,thumbnail_high,...,likeCount,commentCount,privacyStatus,channel_id,channel_title,channel_description,channel_country,channel_thumbnail,channel_subscriberCount,channel_videoCount
3,r4loBN9ffls,Data Analyst Jobs are COOKED 🤯 This is how you...,Is the data analyst job market too saturated? ...,2025-09-22T14:22:16Z,NaN,28,en,en,https://i.ytimg.com/vi/r4loBN9ffls/default.jpg,https://i.ytimg.com/vi/r4loBN9ffls/hqdefault.jpg,...,402.0,6,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
4,NVpxN1vAbNM,H1B is $100K now: How will Big Tech Survive 🤯,NaN,2025-09-20T15:16:16Z,NaN,28,en-US,en,https://i.ytimg.com/vi/NVpxN1vAbNM/default.jpg,https://i.ytimg.com/vi/NVpxN1vAbNM/hqdefault.jpg,...,196.0,54,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
5,yg_K45YtzSs,Data Engineer vs Data Scientist,Here's the difference in less than 60 secs. \n...,2025-09-18T14:22:57Z,NaN,28,en,en,https://i.ytimg.com/vi/yg_K45YtzSs/default.jpg,https://i.ytimg.com/vi/yg_K45YtzSs/hqdefault.jpg,...,130.0,1,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
6,xoptBxQvIT0,Is Big Tech a trap? Why she quit her $200K Sof...,Get the free Content Creator Tool Kit by HubSp...,2025-09-18T14:15:09Z,data science|data scientist|self-taugh data sc...,28,en-US,en,https://i.ytimg.com/vi/xoptBxQvIT0/default.jpg,https://i.ytimg.com/vi/xoptBxQvIT0/hqdefault.jpg,...,69.0,6,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
7,w9k1oXwiOJY,5 Data Analyst Projects You NEED,How to stand out in the Data Analyst Job Marke...,2025-09-15T14:22:30Z,NaN,28,en,en,https://i.ytimg.com/vi/w9k1oXwiOJY/default.jpg,https://i.ytimg.com/vi/w9k1oXwiOJY/hqdefault.jpg,...,625.0,4,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
8,CIfjV-q-g6M,AI Engineer or Software Engineer ft @anjali.gama,AI Engineer vs Software Engineer 😁,2025-09-08T14:22:39Z,NaN,28,en,en,https://i.ytimg.com/vi/CIfjV-q-g6M/default.jpg,https://i.ytimg.com/vi/CIfjV-q-g6M/hqdefault.jpg,...,163.0,8,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
9,Uxr3sbB6h-c,3 Reasons to NOT become a Data Engineer,It's great career but here are 3 reasons to no...,2025-09-06T04:01:21Z,NaN,28,en,en,https://i.ytimg.com/vi/Uxr3sbB6h-c/default.jpg,https://i.ytimg.com/vi/Uxr3sbB6h-c/hqdefault.jpg,...,338.0,6,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
10,PcYZyb93Peg,Data Scientist vs Software Engineer,Here's the difference between in 30 secs\n\nWh...,2025-09-05T04:05:36Z,NaN,28,en,en,https://i.ytimg.com/vi/PcYZyb93Peg/default.jpg,https://i.ytimg.com/vi/PcYZyb93Peg/hqdefault.jpg,...,488.0,12,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
11,n08nWEvdz-I,$2M Tech VP Salary at Amazon ft @EthanEvansVP,Would you give up a $2M job for passion and ba...,2025-08-07T14:28:39Z,NaN,28,en,en,https://i.ytimg.com/vi/n08nWEvdz-I/default.jpg,https://i.ytimg.com/vi/n08nWEvdz-I/hqdefault.jpg,...,456.0,11,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
12,4uHyKtxS1j8,AI Engineer vs Prompt Engineer,AI Engineer vs Prompt Engineer: What's the dif...,2025-08-04T14:23:24Z,NaN,28,en,en,https://i.ytimg.com/vi/4uHyKtxS1j8/default.jpg,https://i.ytimg.com/vi/4uHyKtxS1j8/hqdefault.jpg,...,341.0,12,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
13,z8kAQPEVanw,Software Engineer vs. Data Scientist ft @sajja...,🎯 Software Engineer vs. Data Scientist Edition...,2025-07-31T14:31:04Z,NaN,28,en,en,https://i.ytimg.com/vi/z8kAQPEVanw/default.jpg,https://i.ytimg.com/vi/z8kAQPEVanw/hqdefault.jpg,...,1605.0,17,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
14,_rOwhGL7Hx4,Data Analyst vs Data Scientist vs Machine Lear...,Data Analyst vs Data Scientist vs Machine Lear...,2025-07-28T14:23:48Z,NaN,28,en,hi,https://i.ytimg.com/vi/_rOwhGL7Hx4/default.jpg,https://i.ytimg.com/vi/_rOwhGL7Hx4/hqdefault.jpg,...,575.0,11,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
15,4Fjc1eOj58k,Sr Software Engineer Salary ft @maddyzhang,Sr Software Engineer from Google to Airbnb Sal...,2025-07-25T14:23:20Z,NaN,28,en,en,https://i.ytimg.com/vi/4Fjc1eOj58k/default.jpg,https://i.ytimg.com/vi/4Fjc1eOj58k/hqdefault.jpg,...,149.0,8,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
16,YOBpAHkuprE,10 Learnings from 10 Years in Tech (in 30 seco...,10 years of learnings in 30 seconds 📈 What els...,2025-07-22T14:24:17Z,NaN,28,en,en,https://i.ytimg.com/vi/YOBpAHkuprE/default.jpg,https://i.ytimg.com/vi/YOBpAHkuprE/hqdefault.jpg,...,869.0,10,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
17,MJm_UsF1HJg,Get Hired in 90 Days?,Can you actually get hired in 90 days? Thought...,2025-07-12T14:19:15Z,NaN,28,en,hi,https://i.ytimg.com/vi/MJm_UsF1HJg/default.jpg,https://i.ytimg.com/vi/MJm_UsF1HJg/hqdefault.jpg,...,599.0,11,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
18,nY9UdHZbyxc,Build FREE AI Workflow Using This Tool,#tanka #tankaAI\n\n# Subscribe https://www.you...,2025-07-11T14:30:38Z,data science|data scientist|self-taugh data sc...,28,en-US,en,https://i.ytimg.com/vi/nY9UdHZbyxc/default.jpg,https://i.ytimg.com/vi/nY9UdHZbyxc/hqdefault.jpg,...,205.0,4,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
19,lLCVMc0fIOQ,Why 99% of Self-Taught Programmers Fail,Sign-up for associate data scientist in python...,2025-07-07T14:30:38Z,data science|data scientist|self-taugh data sc...,28,en-US,en,https://i.ytimg.com/vi/lLCVMc0fIOQ/default.jpg,https://i.ytimg.com/vi/lLCVMc0fIOQ/hqdefault.jpg,...,1028.0,64,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
20,ACN21XGzG2w,Microsoft Layoffs 9000 Employees (again),NaN,2025-07-03T14:19:00Z,NaN,28,en-US,en,https://i.ytimg.com/vi/ACN21XGzG2w/default.jpg,https://i.ytimg.com/vi/ACN21XGzG2w/hqdefault.jpg,...,363.0,41,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
21,8_EYTERZ1Ko,7 Things Holding You Back in Your Career 🤯,If you are feeling stuck in your career? These...,2025-06-30T14:23:20Z,NaN,28,en,en,https://i.ytimg.com/vi/8_EYTERZ1Ko/default.jpg,https://i.ytimg.com/vi/8_EYTERZ1Ko/hqdefault.jpg,...,357.0,6,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
22,mmybiM8W8c0,Microsoft Software Engineer Remote ft @anjaligama,What it takes to be remote Software Engineer a...,2025-06-20T03:23:26Z,NaN,28,en,en,https://i.ytimg.com/vi/mmybiM8W8c0/default.jpg,https://i.ytimg.com/vi/mmybiM8W8c0/hqdefault.jpg,...,365.0,6,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
23,q76HaJHuQNc,How I Use Claude as a Data Scientist,Try Claude Code yourself here 👉🏼 http://clau.d...,2025-06-16T14:20:03Z,data science|data scientist|self-taugh data sc...,28,en-US,en,https://i.ytimg.com/vi/q76HaJHuQNc/default.jpg,https://i.ytimg.com/vi/q76HaJHuQNc/hqdefault.jpg,...,373.0,21,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
24,wGiLecwYQrw,How to NOT Negotiate Your Salary ❌,How to NOT Negotiate Your Salary ❌ What's one ...,2025-06-09T14:22:15Z,NaN,27,en,en,https://i.ytimg.com/vi/wGiLecwYQrw/default.jpg,https://i.ytimg.com/vi/wGiLecwYQrw/hqdefault.jpg,...,484.0,3,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
25,Ssl_zIc4FPY,$90K vs $200K Data Analyst?,$90K vs $200K Data Analyst? What's the differe...,2025-05-29T14:20:18Z,NaN,28,en,en,https://i.ytimg.com/vi/Ssl_zIc4FPY/default.jpg,https://i.ytimg.com/vi/Ssl_zIc4FPY/hqdefault.jpg,...,1425.0,28,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
26,Gs7ToLkQv_8,Google i/o 2025 in 60 seconds 😱,NaN,2025-05-26T14:25:00Z,NaN,28,en-US,en,https://i.ytimg.com/vi/Gs7ToLkQv_8/default.jpg,https://i.ytimg.com/vi/Gs7ToLkQv_8/hqdefault.jpg,...,286.0,3,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
27,6Fr-HAzyyzA,Data Scientist vs Software Engineer Roadmap ft...,Choosing between data science and software eng...,2025-05-22T14:20:09Z,NaN,28,en,en,https://i.ytimg.com/vi/6Fr-HAzyyzA/default.jpg,https://i.ytimg.com/vi/6Fr-HAzyyzA/hqdefault.jpg,...,3409.0,22,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
28,_aSAxamhd3A,Bought a Tesla (Almost),#tesla #ev,2025-05-20T14:21:05Z,NaN,2,en,en,https://i.ytimg.com/vi/_aSAxamhd3A/default.jpg,https://i.ytimg.com/vi/_aSAxamhd3A/hqdefault.jpg,...,141.0,13,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
30,BH8hpkOI9l0,2 Life-Changing Resources I Wish I Knew Earlier,2 life-changing resources I wish I knew earlie...,2025-05-15T14:18:19Z,NaN,28,en,en,https://i.ytimg.com/vi/BH8hpkOI9l0/default.jpg,https://i.ytimg.com/vi/BH8hpkOI9l0/hqdefault.jpg,...,549.0,1,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
31,G-wildReV6w,Why AI Coding Agents are the Future 🚀,Try Junie here 👉🏼 https://jb.gg/meet_junie\n\n...,2025-05-12T14:20:00Z,data science|data scientist|self-taugh data sc...,28,en-US,en,https://i.ytimg.com/vi/G-wildReV6w/default.jpg,https://i.ytimg.com/vi/G-wildReV6w/hqdefault.jpg,...,806.0,107,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
32,oRR69xADBOE,Microsoft Engineer at 30 from Fashion ft @anto...,"From fashion design to Microsoft Engineer, she...",2025-05-09T14:21:01Z,NaN,28,en,en,https://i.ytimg.com/vi/oRR69xADBOE/default.jpg,https://i.ytimg.com/vi/oRR69xADBOE/hqdefault.jpg,...,676.0,14,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
33,n5GcunxVkxg,5 Overrated Tech Essentials You Should Stop Ca...,5 overrated tech essentials you should stop ca...,2025-05-05T14:19:20Z,NaN,28,en,en,https://i.ytimg.com/vi/n5GcunxVkxg/default.jpg,https://i.ytimg.com/vi/n5GcunxVkxg/hqdefault.jpg,...,353.0,11,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
34,mbYf_6XTgFY,Principal Solutions Architect ft @cloudwithraj 💻,Salary as Principal Solutions Architect ft @cl...,2025-04-21T14:20:32Z,aws|cloudcomputing|solutionsarchitect,28,en,en,https://i.ytimg.com/vi/mbYf_6XTgFY/default.jpg,https://i.ytimg.com/vi/mbYf_6XTgFY/hqdefault.jpg,...,326.0,9,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
35,DPGFwL4OE-A,Astronaut or Not: Who is WRONG here?,NaN,2025-04-19T14:20:01Z,NaN,28,en-US,en,https://i.ytimg.com/vi/DPGFwL4OE-A/default.jpg,https://i.ytimg.com/vi/DPGFwL4OE-A/hqdefault.jpg,...,190.0,19,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
36,BF9yShzrok0,Data Engineer vs Data Scientist: What's the Di...,Data Engineer vs Data Scientist: What's the Di...,2025-04-18T14:15:59Z,NaN,28,en,en,https://i.ytimg.com/vi/BF9yShzrok0/default.jpg,https://i.ytimg.com/vi/BF9yShzrok0/hqdefault.jpg,...,1143.0,23,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
37,BFxy9CtHXrU,AI Data Analyst in a Spreadsheet 🤯,Try Quadratic AI for free 👉🏼 https://quadratic...,2025-04-15T14:15:02Z,data science|data scientist|self-taugh data sc...,28,en-US,en,https://i.ytimg.com/vi/BFxy9CtHXrU/default.jpg,https://i.ytimg.com/vi/BFxy9CtHXrU/hqdefault.jpg,...,898.0,13,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
38,qxD38vaiX14,Is ChatGPT Operator a flop for $200? Watch thi...,NaN,2025-04-01T14:15:07Z,NaN,28,en-US,en,https://i.ytimg.com/vi/qxD38vaiX14/default.jpg,https://i.ytimg.com/vi/qxD38vaiX14/hqdefault.jpg,...,334.0,8,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
39,Vt4sbBeodKk,What SQL skills to learn as a Data Analyst? ￼,NaN,2025-03-31T14:21:00Z,NaN,28,en-US,en,https://i.ytimg.com/vi/Vt4sbBeodKk/default.jpg,https://i.ytimg.com/vi/Vt4sbBeodKk/hqdefault.jpg,...,699.0,11,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
40,r9UF-NB1QiI,Coding for AI Engineers: What You Need to Lear...,NaN,2025-03-30T14:16:00Z,NaN,28,en-US,en,https://i.ytimg.com/vi/r9UF-NB1QiI/default.jpg,https://i.ytimg.com/vi/r9UF-NB1QiI/hqdefault.jpg,...,409.0,7,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
41,CX8BmrbenU8,How to Write Smart AI Prompts 🔥,NaN,2025-03-29T14:00:22Z,NaN,28,en-US,en,https://i.ytimg.com/vi/CX8BmrbenU8/default.jpg,https://i.ytimg.com/vi/CX8BmrbenU8/hqdefault.jpg,...,206.0,3,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
43,r6S3egd8kPI,I Paid ChatGPT Operator $200 to Apply to 100 J...,Download the AI Prompt Engineer Guide 👉🏼 https...,2025-03-27T14:20:02Z,data science|data scientist|self-taugh data sc...,28,en-US,en,https://i.ytimg.com/vi/r6S3egd8kPI/default.jpg,https://i.ytimg.com/vi/r6S3egd8kPI/hqdefault.jpg,...,342.0,28,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
44,SqTTvrBQm7I,How To Make Your Resume Stand Out With This Se...,NaN,2025-03-21T14:33:43Z,NaN,28,en-US,en,https://i.ytimg.com/vi/SqTTvrBQm7I/default.jpg,https://i.ytimg.com/vi/SqTTvrBQm7I/hqdefault.jpg,...,508.0,7,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
45,7bMnnFsO_sg,10 Year Salary Progression in Big Tech 📈,NaN,2025-03-10T15:02:39Z,NaN,28,en-US,en,https://i.ytimg.com/vi/7bMnnFsO_sg/default.jpg,https://i.ytimg.com/vi/7bMnnFsO_sg/hqdefault.jpg,...,749.0,16,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
46,_Gdj1NHakhs,What is YOUR Next Career?,NaN,2025-03-06T15:25:00Z,NaN,28,en-US,en,https://i.ytimg.com/vi/_Gdj1NHakhs/default.jpg,https://i.ytimg.com/vi/_Gdj1NHakhs/hqdefault.jpg,...,405.0,6,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
47,ELGjEHefi4w,How to Become an $300K AI Engineer in 2025 (co...,AI Engineer for Developers learning track on D...,2025-03-03T15:30:11Z,data science|data scientist|self-taugh data sc...,28,en-US,en,https://i.ytimg.com/vi/ELGjEHefi4w/default.jpg,https://i.ytimg.com/vi/ELGjEHefi4w/hqdefault.jpg,...,4315.0,154,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
48,2r57BkWFLfQ,Return to Office You Said - Task Masking 📈,NaN,2025-03-02T16:07:19Z,NaN,28,en-US,en,https://i.ytimg.com/vi/2r57BkWFLfQ/default.jpg,https://i.ytimg.com/vi/2r57BkWFLfQ/hqdefault.jpg,...,150.0,5,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
49,RE7-goTKAz4,Meta Firing ‘Low-Performers’ WHY?,NaN,2025-02-17T15:23:00Z,NaN,28,en-US,en,https://i.ytimg.com/vi/RE7-goTKAz4/default.jpg,https://i.ytimg.com/vi/RE7-goTKAz4/hqdefault.jpg,...,504.0,39,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
50,9OA757v4FAM,How to Become a Data Scientist in 2025,Sign-up for my newsletter 👉🏼 https:blog.sundas...,2025-02-10T15:10:00Z,data science|data scientist|self-taugh data sc...,28,en-US,en,https://i.ytimg.com/vi/9OA757v4FAM/default.jpg,https://i.ytimg.com/vi/9OA757v4FAM/hqdefault.jpg,...,7844.0,223,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
51,RrZ-Knp7p1s,10 Truth Bombs from 10 Years in Tech 😱,NaN,2025-02-10T03:25:00Z,NaN,28,en-US,en,https://i.ytimg.com/vi/RrZ-Knp7p1s/default.jpg,https://i.ytimg.com/vi/RrZ-Knp7p1s/hqdefault.jpg,...,732.0,17,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288
52,MLidfb72Ue0,Are Gen Z Difficult to Work With 🤯,NaN,2025-02-06T15:25:00Z,NaN,28,en-US,en,https://i.ytimg.com/vi/MLidfb72Ue0/default.jpg,https://i.ytimg.com/vi/MLidfb72Ue0/hqdefault.jpg,...,343.0,16,public,UCteRPiisgIoHtMgqHegpWAQ,Sundas Khalid,Hey! I am Sundas and I help you succeed in the...,US,https://yt3.ggpht.com/ytc/AIdro_kTf9FpyQc2BJ4d...,326000,288

In [11]:
ids1 = set(filtered_df["id"])
ids2 = set(task2["Video_ID"])

# Find missing in df1 compared to df2
missing_in_df1 = ids2 - ids1
print("Missing in df1:", missing_in_df1)

# (Optional) Find extra in df1 compared to df2
extra_in_df1 = ids1 - ids2
print("Extra in df1:", extra_in_df1)

Missing in df1: {'tyj8eNayRM', 'vsloDWDA_8'}
Extra in df1: set()